"use strict";(self.webpackChunkcadence=self.webpackChunkcadence||[]).push([[3685],{8022:(e,i,t)=>{t.r(i),t.d(i,{assets:()=>c,contentTitle:()=>a,default:()=>h,frontMatter:()=>s,metadata:()=>r,toc:()=>l});const r=JSON.parse('{"id":"workflow-troubleshooting/activity-failures","title":"Activity Failures","description":"An activity fails when it encounters an error during its execution. This results in ActivityTaskFailed event in the workflow execution with some details of the error. The different kinds of errors that can be seen in activity failures are listed here.","source":"@site/docs/08-workflow-troubleshooting/02-activity-failures.md","sourceDirName":"08-workflow-troubleshooting","slug":"/workflow-troubleshooting/activity-failures","permalink":"/Cadence-Docs/docs/workflow-troubleshooting/activity-failures","draft":false,"unlisted":false,"editUrl":"https://github.com/cadence-workflow/Cadence-Docs/tree/master/docs/08-workflow-troubleshooting/02-activity-failures.md","tags":[],"version":"current","lastUpdatedBy":"Josue Alexander Ibarra","lastUpdatedAt":1735932231000,"sidebarPosition":2,"frontMatter":{"layout":"default","title":"Activity Failures","permalink":"/docs/workflow-troubleshooting/activity-failures"},"sidebar":"docsSidebar","previous":{"title":"Timeouts","permalink":"/Cadence-Docs/docs/workflow-troubleshooting/timeouts"},"next":{"title":"Retries","permalink":"/Cadence-Docs/docs/workflow-troubleshooting/retries"}}');var n=t(4848),o=t(8453);const s={layout:"default",title:"Activity Failures",permalink:"/docs/workflow-troubleshooting/activity-failures"},a="Activity failures",c={},l=[{value:"Panic errors",id:"panic-errors",level:2},{value:"Custom errors",id:"custom-errors",level:2},{value:"Generic errors",id:"generic-errors",level:2},{value:"Blob Size limits",id:"blob-size-limits",level:2}];function d(e){const i={a:"a",h1:"h1",h2:"h2",header:"header",li:"li",p:"p",ul:"ul",...(0,o.R)(),...e.components};return(0,n.jsxs)(n.Fragment,{children:[(0,n.jsx)(i.header,{children:(0,n.jsx)(i.h1,{id:"activity-failures",children:"Activity failures"})}),"\n",(0,n.jsx)(i.p,{children:"An activity fails when it encounters an error during its execution. This results in ActivityTaskFailed event in the workflow execution with some details of the error. The different kinds of errors that can be seen in activity failures are listed here."}),"\n",(0,n.jsx)(i.h2,{id:"panic-errors",children:"Panic errors"}),"\n",(0,n.jsx)(i.p,{children:"Description: There is a issue in the activity code that is causing a panic."}),"\n",(0,n.jsx)(i.p,{children:"Mitigation: Panics are usually caused by nil pointer dereferences or out-of-range array access and should never be expected in a workflow. Check the stack trace provided in the error details to find where in the activity code, the panic is seen. Fix the rootcause of the panic."}),"\n",(0,n.jsx)(i.h2,{id:"custom-errors",children:"Custom errors"}),"\n",(0,n.jsx)(i.p,{children:"Description: This is a customised error returned by the activity."}),"\n",(0,n.jsx)(i.p,{children:"Mitigation: This is a way of facilitating error handling done within the activity code. Check your activity code to find where it returns a NewCustomError with some information. This is ideally an expected error scenario and should be handled within the workflow that executed the activity."}),"\n",(0,n.jsxs)(i.p,{children:["Read more about ",(0,n.jsx)(i.a,{href:"https://cadenceworkflow.io/docs/go-client/error-handling/",children:"error handling"})]}),"\n",(0,n.jsx)(i.h2,{id:"generic-errors",children:"Generic errors"}),"\n",(0,n.jsx)(i.p,{children:"Description: This is an error returned by the activity."}),"\n",(0,n.jsx)(i.p,{children:"Mitigation: This error is caused by something unexpected within the activity code, typically due to a downstream service that your activity communicates with. Cadence does not know anything about it and just puts all unknown errors in this category. Check your activity code to find the potential error cases. This is ideally an unexpected error scenario and should be debugged further to fix the rootcause."}),"\n",(0,n.jsxs)(i.p,{children:["Read more about ",(0,n.jsx)(i.a,{href:"https://cadenceworkflow.io/docs/go-client/error-handling/",children:"error handling"})]}),"\n",(0,n.jsx)(i.h2,{id:"blob-size-limits",children:"Blob Size limits"}),"\n",(0,n.jsxs)(i.p,{children:["Description: This is an error caused when a decision contains data that exceeds the configured limit. If an API call contains data that exceeds the limit, the API call will fail. These limits are dynamically configured per cadence domain ",(0,n.jsx)(i.a,{href:"https://github.com/cadence-workflow/cadence/blob/master/common/dynamicconfig/constants.go#L2938",children:"link to code"}),"."]}),"\n",(0,n.jsx)(i.p,{children:"Mitigation: It is recommended to store the data elsewhere in another storage technology and using its reference. The workflow can then take that reference and pass it around to other parts of the workflow to retrieve that data."}),"\n",(0,n.jsx)(i.p,{children:"Cadence enforces the maximum blob size in several cases. Some of these are:"}),"\n",(0,n.jsxs)(i.ul,{children:["\n",(0,n.jsx)(i.li,{children:"Signal input"}),"\n",(0,n.jsx)(i.li,{children:"Workflow input and output"}),"\n",(0,n.jsx)(i.li,{children:"Workflow continueAsNew input"}),"\n",(0,n.jsx)(i.li,{children:"Activity input and output"}),"\n",(0,n.jsx)(i.li,{children:"Workflow/Activity error_details"}),"\n",(0,n.jsx)(i.li,{children:"Record marker"}),"\n",(0,n.jsx)(i.li,{children:"Heartbeat details"}),"\n"]})]})}function h(e={}){const{wrapper:i}={...(0,o.R)(),...e.components};return i?(0,n.jsx)(i,{...e,children:(0,n.jsx)(d,{...e})}):d(e)}},8453:(e,i,t)=>{t.d(i,{R:()=>s,x:()=>a});var r=t(6540);const n={},o=r.createContext(n);function s(e){const i=r.useContext(o);return r.useMemo((function(){return"function"==typeof e?e(i):{...i,...e}}),[i,e])}function a(e){let i;return i=e.disableParentContext?"function"==typeof e.components?e.components(n):e.components||n:s(e.components),r.createElement(o.Provider,{value:i},e.children)}}}]);